joystick_mapper:
  ros__parameters:
    joy_topic: /joy
    output_topic: /joystick_cartesian_command
    mode_request_topic: /mode_request
    deadzone: 0.2
    modes:
      names: [b1, b2]
      b1:
        angular_output_frame_id: base_link
        axes:
          linear_x: {index: 0, scale: 1.0}
          linear_y: {index: 1, scale: 1.0}
          linear_z: {index: -1, scale: 1.0}
          angular_x: {index: -1, scale: 1.0}
          angular_y: {index: -1, scale: 1.0}
          angular_z: {index: -1, scale: 1.0}
      b2:
        angular_output_frame_id: effector_frame
        axes:
          linear_x: {index: -1, scale: 1.0}
          linear_y: {index: -1, scale: 1.0}
          linear_z: {index: 0, scale: 1.0}
          angular_x: {index: -1, scale: 1.0}
          angular_y: {index: -1, scale: 1.0}
          angular_z: {index: 1, scale: 1.0}
    snake_button_index: 10
    snake_button_mode: hold
    local_mode_button_index: 11
    local_mode_button_mode: toggle
    gripper_button_index: 0
    gripper_button_mode: toggle
    gripper_command_topic: "/gripper_controller/commands"
    gripper_open_position: 0.2
    gripper_close_position: 1.1
    debug: false
