joystick_mapper:
  ros__parameters:
    joy_topic: "/joy"
    output_topic: "/joystick_cartesian_command"
    mode_request_topic: "/mode_request"
    output_frame_id: "base_link"
    orientation_frame_id: "effector_frame" # "base_frame", "effector_frame", or "hybrid_frame"
    deadzone: 0.2
    local_mode_button_index: 1
    local_mode_button_mode: toggle
    modes:
      names: ["b1", "b2", "b3"]
      b1:
        axes:
          linear_x:
            index: 0
            scale: 1.0
          linear_y:
            index: 1
            scale: 1.0
          linear_z:
            index: -1
            scale: 1.0
          angular_x:
            index: -1
            scale: 1.0
          angular_y:
            index: -1
            scale: 1.0
          angular_z:
            index: -1
            scale: 1.0
      b2:
        axes:
          linear_x:
            index: -1
            scale: 1.0
          linear_y:
            index: -1
            scale: 1.0
          linear_z:
            index: 0
            scale: 1.0
          angular_x:
            index: -1
            scale: 1.0
          angular_y:
            index: -1
            scale: 1.0
          angular_z:
            index: 1
            scale: 1.0
      b3:
        axes:
          linear_x:
            index: -1
            scale: 1.0
          linear_y:
            index: -1
            scale: 1.0
          linear_z:
            index: -1
            scale: 1.0
          angular_x:
            index: 0
            scale: 1.0
          angular_y:
            index: 1
            scale: 1.0
          angular_z:
            index: -1
            scale: 1.0
    jaco_button_index: 11
    jaco_button_mode: toggle
    snake_button_index: 10
    snake_button_mode: hold
    home_button_index: 4
    home_button_mode: hold
